language: node_js
node_js:
  - "5.7.0"
  - "5.0.0"
  - "4.3.1"
  - "4.0.0"
deploy:
  provider: npm
  email: "dev@knowre.com"
  api_key:
    secure: "Dlf8lnyAQdpZQTL01IXiXeH3pFxYGhJvciZ3K/t7C2udBiyAJ6BQa82VZy2qqJqqIDSCQ6+RB74bj4HAqdv7CwZFPIGeGkdDDbSMVfJ5H7nMwhkhXvE5cs4HJq0BEVl3WQyJ4s8cvlBz7TPMdITIIjrd1SiU3U/NjHHLkS0Pwf3zDeToO9vzNlCqLMBf3hlrd2nSCeHkb4TAMrvVbIVCP0zdAjYIpoQozOS8G12n1NoeLIdPyTcP9xXaPtUl/L+IS+onqWs+DZmMzDFvUaIcxpczknKekAmipG4BAAjT2sXNlSsR6DWJQttytcsE62q1K27Bf/IK/GuyswDkwJkrfwoEw032nPSxSYnnRIWMiV5jYB3CxnmSm86RIlx+aBFAgkld7FnTrrcQFT4e8A8DAXGGUH5P/tqrKvp8MGtfDzol/8CGSuq6b2WOZPMXOyptTE5BQN80w+DU25vYzTkQpbEIGauQzBGFMdk5u856yUmB2MfQvo91EWb0dCii41Tm7V9AM+aV7HNSBjY3UwBXuaGIrmHks9DZj/3RwDRBY6J1PLGZ+m7dE+3raBu5KeCwcaWUJbd2uVNreMfgYAO0vZZr2o4QoQhqEOV0ec5MSPazF5nMjK35cT/R4mYt/NBw5xyq0Bia3yhKNLjdvoGZrsBaIXkj8nPOYBDf4LM49dg="
  on:
    branch: stable
    node_js: "5.7.0"
notifications:
  slack:
    secure: "WCV//5848CCNmQrPONHIYPA9vVcgCJFdnpY8A+l1UsHP4yRrm8+nPGx7oLa9LJv6cDPoF1QDdt/TlR8qM2FEtH7kmx6btp8W+cXhHXCu1VlUrM7KX2kQH7LjIIzCLIVhWMVTNtEFr1lZJJVGznDUmVRVrhTUYKN39c8pE4jV02gx6pMSCoqs1Y7veIWUsICeOwQ5ZMuctOhsI2890iKu3uSK5P55flCiQ3Qhivj6EcwvY5ZoGWBFrh8brozOzK8Smi/Q/OfXUSTQMXDYIpEURyf2x/OW+7X8Xryn+74URXJ4ytboodbzd8SgyBvAElBVMeLLbXkFM0gP0AkMFuUERKB7Xdc3kJZC7x5yGwSJe51+MNht5IEXJbY+2f/ABKwKdmBN92fwvkHLeg2+W8okiOxvfskNEBFwYbGM3hQEr5oF4FL6zDBnFxAK8J+LnHXrU1+QS9Vy4ct/CoLgQ2FJLQ9Fh7OV4ouqI0jboYxTUapikAkXgNb+nC7mFbNEQosom+bF0vXoIbhinwkESp/aCHBWIxTwgX5GKXTOU6tvuifldOHwKMvz5y8mQDUIhg0h1sbYALlh7cN5tjm6cf18Z3nZVX1Lwfvregj4Bn+B6I0s3f2JpLtKA43Q9tjp7xP/mfxVilwbIeLo6jn2ZpwRlvd1dcEglGT+36lvdEfE3pQ="
